[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
